spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    locations: classpath:db/migration_dev

  data:
    redis:
      host: localhost
      port: 6379