server:
  port: ${PORT:8080}

spring:
  application:
    name: farm-smart-management

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:587}
    username: ${SMTP_MAIL}
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN

app:
  front-end-url: ${FRONT_END_URL:http://localhost:3000}
  jwt:
    secret: ${SIGNER_KEY}
    expiration: ${EXPIRATION:3600000}
    refresh-expiration: 604800000

management:
  health:
    mail:
      enabled: false

# ── SePay Payment ────────────────────────────────────────────────────
payment:
  sepay:
    merchant-code: ${SEPAY_MERCHART_CODE}          # ← sửa 672789 → 762965
    secret-key:    ${SEPAY_SECRET_KEY}# ← lấy từ dashboard
    payment-url: ${SEPAY_PAYMENT_URL}
    return-url: ${SEPAY_RETURN_URL}